save-position-on-quit
# Utilisation de VAAPI pour le décodage matériel
#hwdec=vaapi
#vo=gpu
##vo=vaapi
#gpu-context=x11egl
#
## Activation du profil GPU haute qualité
#profile=gpu-hq
#
## Synchronisation vidéo pour éviter le tearing
#video-sync=display-resample
#interpolation
#tscale=oversample
#
## Audio
#ao=pulse
#
## Cache pour la lecture réseau (optionnel)
#cache=yes
